var mongoose = require('mongoose');
    express = require('express');
    cors = require('cors');
    morgan = require('morgan');
    config = require('./config/database');
    routes = require('./routes/routes');
    bodyParser = require('body-parser');
    session = require('express-session');
//const swaggerUi = require('swagger-ui-express');
//const swaggerDocument = require('./config/swagger.json');
//swagger = require("swagger-node-express");
//const swaggerJsdoc = require('swagger-jsdoc')

const options = {
/*  swaggerDefinition: {
    // Like the one described here: https://swagger.io/specification/#infoObject
    info: {
      title: 'Test API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
    },
  },  */
  explorer : true,
  // List of files to be processes. You can also set globs './routes/*.js'
//  apis: routes,
};

//const specs = swaggerJsdoc(options);


mongoose.connection.on('open', function(){
    console.log('Mongo is connected');
    var app = express();
    app.use(morgan('dev'));
    app.use(cors());
    app.use(bodyParser.urlencoded({extended: false}));
    app.use(bodyParser.json()); 

    //app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument,options));
    app.use(routes);     

    let port = process.env.PORT;
if (port == null || port == "") {
        port = 3333;
   }
   console.log('server is running on port'+ port);

app.listen(port);

})

